<?php

namespace App\Http\Controllers\Admin;

use App\Events\AdminNotificationDispatched;
use App\Http\Controllers\Controller;
use App\Models\ActivityLog;
use App\Models\Notification;
use App\Models\NotificationCampaign;
use App\Models\Scopes\TenantScope;
use App\Models\User;
use App\Services\AdminNotificationDispatcher;
use App\Services\BranchDashboardContext;
use App\Services\BranchDashboardScope;
use App\Services\DashboardBranchFilter;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use Illuminate\Validation\ValidationException;
use Inertia\Inertia;

class AdminNotificationController extends Controller
{
    public function index(Request $request)
    {
        $scope = $this->branchScope($request);
        $branchFilter = app(DashboardBranchFilter::class);
        $selectedBranchId = $branchFilter->selectedBranchId($request, $scope);
        $canCreateNotifications = $request->user()->canUseAdminPermission('notifications', 'send');

        // Campaign and recipient-delivery ledgers are not an operational
        // inbox. This screen deliberately shows messages generated by the
        // system plus the audited operations that caused meaningful changes.
        $systemNotificationQuery = Notification::withoutGlobalScope(TenantScope::class)
            ->withTrashed()
            ->whereNull('campaign_id');
        $this->restrictNotificationsToScope($systemNotificationQuery, $scope, $selectedBranchId);

        $systemNotifications = (clone $systemNotificationQuery)
            ->with([
                'user' => function ($recipient) use ($scope): void {
                    $recipient->select(['id', 'name', 'role', 'branch_id']);
                    $this->restrictUsersToScope($recipient->getQuery(), $scope);
                },
            ])
            ->latest('id')
            ->limit(60)
            ->get()
            ->map(fn (Notification $notification) => [
                'id' => 'notification-'.$notification->id,
                'kind' => 'notification',
                'title' => $notification->titleFor(),
                'detail' => $notification->bodyFor(),
                'actor' => $notification->user?->name,
                'at' => $notification->created_at,
            ]);

        $activityQuery = ActivityLog::query()->with('user:id,name,branch_id');
        if ($scope->hasBranchScope()) {
            $activityQuery->whereHas('user', fn (Builder $actor) => $scope->restrictUsers($actor));
        } elseif ($selectedBranchId) {
            $activityQuery->whereHas('user', fn (Builder $actor) => $actor->where('branch_id', $selectedBranchId));
        }

        $activities = $activityQuery
            ->latest('id')
            ->limit(60)
            ->get()
            ->map(fn (ActivityLog $activity) => [
                'id' => 'activity-'.$activity->id,
                'kind' => 'activity',
                'title' => $this->activityTitle($activity->action),
                'detail' => $this->activityDetail($activity),
                'actor' => $activity->user?->name,
                'at' => $activity->created_at,
            ]);

        $recentOperations = $systemNotifications
            ->merge($activities)
            ->sortByDesc(fn (array $item) => $item['at']?->getTimestamp() ?? 0)
            ->take(80)
            ->map(fn (array $item) => [
                ...$item,
                'created_at' => $item['at']?->diffForHumans(),
            ])
            ->values();

        $props = [
            'recentOperations' => $recentOperations,
            // A branch selection is an audit view. Do not make its recipient
            // count look local while a POST would still be a platform-wide
            // broadcast; clear the filter to send a global campaign.
            'canCreateNotifications' => $canCreateNotifications && (! $scope->isSuperAdmin() || ! $selectedBranchId),
            'branchFilter' => $branchFilter->payload($request, $scope),
            'counts' => [
                'system' => (clone $systemNotificationQuery)->count(),
                'operations' => (clone $activityQuery)->count(),
            ],
        ];

        // The recipient picker contains up to 500 names and phone numbers.
        // Viewing sent campaigns does not require access to that directory.
        if ($canCreateNotifications) {
            $props['recipients'] = $this->notificationRecipients($scope, $selectedBranchId)
                ->orderBy('name')
                ->limit(500)
                ->get(['id', 'name', 'phone', 'role'])
                ->map(fn (User $user) => [
                    'id' => $user->id,
                    'name' => $user->name,
                    'phone' => $user->phone,
                    'role' => $user->role,
                ]);
        }

        return Inertia::render('Admin/Notifications', $props);
    }

    public function store(Request $request, AdminNotificationDispatcher $dispatcher)
    {
        $scope = $this->branchScope($request);
        $audience = (string) $request->input('audience');
        $requiresTarget = in_array($audience, NotificationCampaign::TARGETED_AUDIENCES, true);
        $targetRoles = match ($audience) {
            'merchant' => ['merchant'],
            'courier' => User::COURIER_ROLES,
            default => User::NOTIFICATION_RECIPIENT_ROLES,
        };

        $data = $request->validate([
            'audience' => ['required', Rule::in(NotificationCampaign::AUDIENCES)],
            'target_user_id' => [
                Rule::requiredIf($requiresTarget),
                // Never silently turn a stale "specific user" selection into
                // a broadcast when an operator switches back to a general
                // audience in the dashboard.
                Rule::prohibitedIf(! $requiresTarget),
                'nullable',
                'integer',
                Rule::exists('users', 'id')->where(fn ($query) => $query
                    ->whereIn('role', $targetRoles)
                    ->where('status', 'active')
                    ->whereNull('deleted_at')),
            ],
            'type' => ['required', Rule::in(['announcement', 'system', 'account', 'finance', 'order'])],
            'title_ar' => ['required', 'string', 'max:160'],
            'title_en' => ['nullable', 'string', 'max:160'],
            'title_ku' => ['nullable', 'string', 'max:160'],
            'body_ar' => ['nullable', 'string', 'max:1000'],
            'body_en' => ['nullable', 'string', 'max:1000'],
            'body_ku' => ['nullable', 'string', 'max:1000'],
        ]);

        if ($scope->hasBranchScope()) {
            $this->ensureTargetBelongsToBranch($data, $targetRoles, $scope);
            $campaign = $this->dispatchToBranch($request->user(), $data, $scope);
        } else {
            // Preserve the established platform dispatcher verbatim for the
            // super administrator and existing platform employees.
            $campaign = $dispatcher->dispatch($request->user(), $data);
        }

        return back()->with('success', __('Notification sent to :count recipients.', [
            'count' => $campaign->recipient_count,
        ]));
    }

    private function activityTitle(string $action): string
    {
        return match (true) {
            str_contains($action, 'document') => 'مراجعة وثيقة',
            str_contains($action, 'chat') || str_contains($action, 'message') => 'رسالة أو محادثة',
            str_contains($action, 'order') => 'حركة على طلب',
            str_contains($action, 'courier') => 'حركة مندوب',
            str_contains($action, 'merchant') => 'حركة تاجر',
            str_contains($action, 'finance') || str_contains($action, 'cashbox') => 'حركة مالية',
            str_contains($action, 'branch') => 'حركة فرع',
            str_contains($action, 'notification') => 'إشعار أو رسالة مرسلة',
            str_contains($action, 'settings') || str_contains($action, 'content') => 'تحديث الإعدادات',
            default => 'حركة في النظام',
        };
    }

    private function activityDetail(ActivityLog $activity): string
    {
        $data = $activity->data ?? [];
        $parts = [];

        foreach (['document_type', 'track_no', 'reason', 'status', 'verified'] as $key) {
            if (isset($data[$key]) && $data[$key] !== '') {
                $parts[] = is_bool($data[$key]) ? ($data[$key] ? 'نعم' : 'لا') : (string) $data[$key];
            }
        }

        return $parts ? implode(' · ', $parts) : str_replace(['.', '_'], [' · ', ' '], $activity->action);
    }

    private function branchScope(Request $request): BranchDashboardScope
    {
        $scope = app(BranchDashboardContext::class)->fromRequest($request);

        // Never allow an inactive or unassigned branch account to fall back
        // to the platform-wide notification behaviour.
        abort_if($scope->requiresBranchScope() && ! $scope->hasBranchScope(), 403);

        return $scope;
    }

    /** @param Builder<User> $users */
    private function restrictUsersToScope(Builder $users, BranchDashboardScope $scope): void
    {
        if ($scope->hasBranchScope()) {
            $scope->restrictUsers($users);
        }
    }

    /** @param Builder<Notification> $notifications */
    private function restrictNotificationsToScope(Builder $notifications, BranchDashboardScope $scope, ?int $selectedBranchId = null): Builder
    {
        $notifications
            ->withoutGlobalScope(TenantScope::class)
            ->withTrashed();

        $branchId = $scope->hasBranchScope() ? $scope->branchId() : $selectedBranchId;

        if ($branchId) {
            $notifications->whereHas('user', function (Builder $recipient) use ($scope, $branchId): void {
                $recipient->withoutGlobalScope(TenantScope::class);
                if ($scope->hasBranchScope()) {
                    $scope->restrictUsers($recipient);
                } else {
                    $recipient->where('branch_id', $branchId);
                }
            });
        }

        return $notifications;
    }

    /** @return Builder<User> */
    private function notificationRecipients(BranchDashboardScope $scope, ?int $selectedBranchId = null): Builder
    {
        $recipients = User::withoutGlobalScope(TenantScope::class)
            ->whereIn('role', User::NOTIFICATION_RECIPIENT_ROLES)
            ->where('status', 'active');
        if ($scope->hasBranchScope()) {
            $this->restrictUsersToScope($recipients, $scope);
        } elseif ($selectedBranchId) {
            $recipients->where('branch_id', $selectedBranchId);
        }

        return $recipients;
    }

    /**
     * @param  array<string, mixed>  $payload
     * @param  array<int, string>  $targetRoles
     */
    private function ensureTargetBelongsToBranch(array $payload, array $targetRoles, BranchDashboardScope $scope): void
    {
        if (! in_array($payload['audience'], NotificationCampaign::TARGETED_AUDIENCES, true)) {
            return;
        }

        $target = $this->notificationRecipients($scope)
            ->whereIn('role', $targetRoles)
            ->whereKey($payload['target_user_id'])
            ->first();

        if (! $target) {
            throw ValidationException::withMessages([
                // Keep a foreign branch account indistinguishable from an
                // invalid id to avoid turning this endpoint into a directory.
                'target_user_id' => [__('Choose an active recipient from your branch.')],
            ]);
        }
    }

    /**
     * Branch-local counterpart to AdminNotificationDispatcher. The shared
     * dispatcher intentionally broadcasts platform-wide, so passing it a
     * branch manager would leak a general-audience campaign to other areas.
     *
     * @param  array<string, mixed>  $payload
     */
    private function dispatchToBranch(User $actor, array $payload, BranchDashboardScope $scope): NotificationCampaign
    {
        $payload += [
            'target_user_id' => null,
            'title_en' => null,
            'title_ku' => null,
            'body_ar' => null,
            'body_en' => null,
            'body_ku' => null,
        ];

        return DB::transaction(function () use ($actor, $payload, $scope): NotificationCampaign {
            $recipients = $this->branchRecipientsForAudience($payload, $scope)
                ->get(['id', 'tenant_id']);

            if ($recipients->isEmpty()) {
                throw ValidationException::withMessages([
                    'audience' => __('No active recipients match the selected audience.'),
                ]);
            }

            $campaign = NotificationCampaign::create([
                'created_by' => $actor->id,
                'audience' => $payload['audience'],
                'target_user_id' => in_array($payload['audience'], NotificationCampaign::TARGETED_AUDIENCES, true)
                    ? $payload['target_user_id']
                    : null,
                'type' => $payload['type'],
                'title_ar' => $payload['title_ar'],
                'title_en' => $payload['title_en'] ?: null,
                'title_ku' => $payload['title_ku'] ?: null,
                'body_ar' => $payload['body_ar'] ?: null,
                'body_en' => $payload['body_en'] ?: null,
                'body_ku' => $payload['body_ku'] ?: null,
                'recipient_count' => $recipients->count(),
                'sent_at' => now(),
            ]);

            $notificationIds = [];
            $now = now();

            foreach ($recipients as $recipient) {
                $delivery = Notification::create([
                    'campaign_id' => $campaign->id,
                    'tenant_id' => $recipient->tenant_id,
                    'user_id' => $recipient->id,
                    'type' => $payload['type'],
                    'title_ar' => $payload['title_ar'],
                    'title_en' => $payload['title_en'] ?: null,
                    'title_ku' => $payload['title_ku'] ?: null,
                    'body_ar' => $payload['body_ar'] ?: null,
                    'body_en' => $payload['body_en'] ?: null,
                    'body_ku' => $payload['body_ku'] ?: null,
                    'data' => [
                        'source' => 'dashboard',
                        'campaign_id' => $campaign->id,
                        'audience' => $campaign->audience,
                        'recipient_user_id' => $recipient->id,
                        'recipient_tenant_id' => $recipient->tenant_id,
                        'sent_at' => $now->toIso8601String(),
                    ],
                    'created_at' => $now,
                ]);

                $notificationIds[] = $delivery->id;
            }

            DB::afterCommit(function () use ($campaign, $recipients, $notificationIds): void {
                AdminNotificationDispatched::dispatch(
                    $campaign->id,
                    $recipients->pluck('id')->map(fn ($id) => (int) $id)->all(),
                    $recipients->pluck('tenant_id')->map(fn ($id) => $id === null ? null : (int) $id)->all(),
                    $notificationIds,
                );
            });

            return $campaign;
        });
    }

    /**
     * @param  array{audience:string,target_user_id?:int|null}  $payload
     * @return Builder<User>
     */
    private function branchRecipientsForAudience(array $payload, BranchDashboardScope $scope): Builder
    {
        $recipients = $this->notificationRecipients($scope)->orderBy('id');

        return match ($payload['audience']) {
            'merchants' => $recipients->where('role', 'merchant'),
            'merchant' => $recipients->where('role', 'merchant')->whereKey($payload['target_user_id']),
            'couriers' => $recipients->whereIn('role', User::COURIER_ROLES),
            'courier' => $recipients->whereIn('role', User::COURIER_ROLES)->whereKey($payload['target_user_id']),
            'pickup_couriers' => $recipients->where('role', 'pickup_courier'),
            'delivery_couriers' => $recipients->where('role', 'delivery_courier'),
            'transporters' => $recipients->where('role', 'transporter'),
            'user' => $recipients->whereKey($payload['target_user_id']),
            default => $recipients,
        };
    }
}
